### ISSUE TITLE
CssSyntaxError when using Stylelint on Svelte files with SCSS

### ISSUE THREAD

**Issue by spaceninja** [ota-meshi/stylelint-config-html#12]
We've got a SvelteKit project that's running svelte-preprocess to allow for SCSS in our .svelte files. That part's working great.

We've got your config running to allow Stylelint to lint the CSS in our .svelte files. That part's working great.

The only problem we've run into is that if we use SCSS comments in our .svelte files, Stylelint throws an error:

> Unknown word (CssSyntaxError)

The problem goes away if we use CSS comments.

I'm not sure how we can address this. Any help or pointers in the right direction would be really appreciated!

I understand this may not be caused by your stylelint config, I'm just trying to find the best place to look for help.

## Reproduction Instructions

- @sveltejs/kit @ next
- svelte @ 3.44.0
- svelte-preprocess @ 4.94
- stylelint @ 14.2.0
- stylelint-config-html @ 1.0.0
- stylelint-config-recommended-scss @ 5.0.2

### .stylelintrc.js

```js
module.exports = {
  extends: [
    'stylelint-config-recommended-scss',
    'stylelint-config-html/svelte',
  ],
  rules: {...}
};```

**Comment by ota-meshi** [comment]
Thank you for posting this issue.
Did you explicitly install `postcss-scss` and `postcss`? If you have not installed it, please install it.
If it's installed, I don't know the cause, so could you share a repository that can reproduce the problem?

**Comment by spaceninja** [comment]
The repo is here: https://github.com/cloudfour/linkedin-learning-quiz

We don't explicitly have postcss or postcss-scss installed, but they're both listed in the lock file.

**Comment by ota-meshi** [comment]
I can't access your repository.

**Comment by spaceninja** [comment]
Oh shoot, sorry, I forgot it's a private repo.

Let me see if I can spin up a reproduction for you.

**Comment by spaceninja** [comment]
Okay, here you go — apologies if this repo is a bit of a mess, I literally just copied the private repo and ripped out anything client-related.

https://github.com/cloudfour/sveltekit-scss-stylelint-repro

You can run `npm ci` and then `npm run lint` to see Stylelint fail.

The file with the failing SCSS comment is `src/lib/views/home.svelte`

**Comment by ota-meshi** [comment]
I found out why it didn't work.
postcss-html does not recognize the `type` attribute. Use the `lang` attribute instead.

```diff
- <style type="scss">
+ <style lang="scss">
```

I've never used SCSS with Svelte, is it common to use the `type` attribute?

**Comment by ota-meshi** [comment]
Looking at the docs it seems to use the `lang` attribute.

https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#scss-sass

**Comment by spaceninja** [comment]
OMG you're totally right.

It's astonishing preprocessing _ever_ worked since we got the syntax wrong. Thank you so much!
